apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/libvirt-provider/config/default?ref=5806bdcf0c292780a6a7f871127755ae223439b1
  - role-binding.yaml
  - role.yaml

images:
  - name: machinepoollet
    newName: ghcr.io/ironcore-dev/ironcore-machinepoollet
    digest: sha256:7a4584539882e9fb22f213756b2cfe37f8f1d43896351545fc4192ce9825d970
  - name: libvirt-provider
    newName: ghcr.io/ironcore-dev/libvirt-provider
    digest: sha256:96aecb77601e5109645ff595f0da105f5cc2d89bd578dd2d502a6129ff0e764b

patches:
  - path: patch-manager-daemonset.yaml
